name: CI Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
    test:
      - name: Run tests
        run: node test.js
      - name: Notify success
        if: success()
        run: echo "Build and tests passed successfully"
      - name: Notify failure
        if: failure()
        run: echo "Build or tests failed"
